name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint test
        run: npm run lint
      - name: Buid project
        run: npm run build
      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: buid
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Deploy
        run: |
          echo Deploying files from dist ...
