name: Check lint before commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install project dependencies
        run: npm ci
      - name: Lint project
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Deploy
        run: |
          echo Deploying ...
